workflows:
  ios_unsigned:
    name: iOS unsigned .app builder
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Clean and prepare
        script: |
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Generate localization files
        script: flutter gen-l10n

      - name: Build iOS .app (no signing)
        script: flutter build ios --release --no-codesign

      - name: Zip the Runner.app
        script: |
          mkdir -p build/ios/app
          cp -r build/ios/iphoneos/Runner.app build/ios/app/
          cd build/ios
          zip -r runner.app.zip app

    artifacts:
      - build/ios/runner.app.zip


