// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeOjY3av0aC0SP8K3cTLg-ugho1izhd1M',
    appId: '1:273120843685:android:0883cb04532815f56c3a4c',
    messagingSenderId: '273120843685',
    projectId: 'savingcalculat0r',
    storageBucket: 'savingcalculat0r.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZ3gV2B8U7Sd45ymakv7NclG8drlIVQw',
    appId: '1:273120843685:ios:15ca49f197a4312d6c3a4c',
    messagingSenderId: '273120843685',
    projectId: 'savingcalculat0r',
    storageBucket: 'savingcalculat0r.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS33gjiCcpvS5dgFqB-DbUksUSGPkbgvc',
    appId: '1:273120843685:web:fe71449aa0b405f66c3a4c',
    messagingSenderId: '273120843685',
    projectId: 'savingcalculat0r',
    authDomain: 'savingcalculat0r.firebaseapp.com',
    storageBucket: 'savingcalculat0r.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZ3gV2B8U7Sd45ymakv7NclG8drlIVQw',
    appId: '1:273120843685:ios:15ca49f197a4312d6c3a4c',
    messagingSenderId: '273120843685',
    projectId: 'savingcalculat0r',
    storageBucket: 'savingcalculat0r.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS33gjiCcpvS5dgFqB-DbUksUSGPkbgvc',
    appId: '1:273120843685:web:b4ebb71297ccf96a6c3a4c',
    messagingSenderId: '273120843685',
    projectId: 'savingcalculat0r',
    authDomain: 'savingcalculat0r.firebaseapp.com',
    storageBucket: 'savingcalculat0r.firebasestorage.app',
  );

}