// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsoCHFI034T5Oamt65WHVzbs0NRDQ8Y20',
    appId: '1:559115929002:android:82d5d5f11d6ebb0e65d7d3',
    messagingSenderId: '559115929002',
    projectId: 'recipeapp-6f3b2',
    databaseURL: 'https://recipeapp-6f3b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipeapp-6f3b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPz1ttEjEQNeunNqOghAfC8rBjtwhaTvE',
    appId: '1:559115929002:ios:b5ed429df9f4b40c65d7d3',
    messagingSenderId: '559115929002',
    projectId: 'recipeapp-6f3b2',
    databaseURL: 'https://recipeapp-6f3b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipeapp-6f3b2.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOvr0VyZDqRKMjt2bLtqUVxe1ZKKq6x4',
    appId: '1:559115929002:web:36e7f376edabb15365d7d3',
    messagingSenderId: '559115929002',
    projectId: 'recipeapp-6f3b2',
    authDomain: 'recipeapp-6f3b2.firebaseapp.com',
    databaseURL: 'https://recipeapp-6f3b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipeapp-6f3b2.firebasestorage.app',
    measurementId: 'G-7L38EECV24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPz1ttEjEQNeunNqOghAfC8rBjtwhaTvE',
    appId: '1:559115929002:ios:b5ed429df9f4b40c65d7d3',
    messagingSenderId: '559115929002',
    projectId: 'recipeapp-6f3b2',
    databaseURL: 'https://recipeapp-6f3b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipeapp-6f3b2.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASOvr0VyZDqRKMjt2bLtqUVxe1ZKKq6x4',
    appId: '1:559115929002:web:b41d58161ea5e04b65d7d3',
    messagingSenderId: '559115929002',
    projectId: 'recipeapp-6f3b2',
    authDomain: 'recipeapp-6f3b2.firebaseapp.com',
    databaseURL: 'https://recipeapp-6f3b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipeapp-6f3b2.firebasestorage.app',
    measurementId: 'G-8NJPKQN9LB',
  );

}